### ISSUE TITLE
client gets stuck if "/" is used after fileset

### ISSUE THREAD

**Issue by dim3nsi0n32** [ethernity-cloud/mvp-pox-client#3]
When running the command "./pox-do -s scripts/cos-bench/cos-bench.py  -f scripts/cos-bench/fileset/" it seems the Client gets stuck at "2021-06-21 13:42:45.838875 Sending payload to IPFS..."

It works ok with "./pox-do -s scripts/cos-bench/cos-bench.py  -f scripts/cos-bench/fileset" (note missing / after fileset)

**Comment by ethernity-cloud** [comment]
It works ok with "./pox-do -s scripts/cos-bench/cos-bench.py -f scripts/cos-bench/fileset" (note missing / after fileset)
